### ISSUE TITLE
Test suite build broken

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-test#1223]
@frivoal broke the build in 395e39f54906cca78dcd8377099a52a30efb246a:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "tools/build.py", line 8, in <module>
    import sys
  File "tools/build.py", line 306, in build
    self.gatherTests(dir)
  File "tools/build.py", line 174, in gatherTests
    self.gatherTests(subDirPath)
  File "tools/build.py", line 174, in gatherTests
    self.gatherTests(subDirPath)
  File "tools/build.py", line 169, in gatherTests
    self.testSuites[testSuiteName].addTestsByList(dir, suiteFileNames[testSuiteName])
  File "tools/w3ctestlib/Suite.py", line 44, in addTestsByList
    self.addGroup(group)
  File "tools/w3ctestlib/Suite.py", line 60, in addGroup
    master.merge(group)
  File "tools/w3ctestlib/Groups.py", line 155, in merge
    self.support = SourceSet.combine(self.support, other.support, self.ui)
  File "tools/w3ctestlib/Sources.py", line 256, in combine
    return a.merge(b, ui)
  File "tools/w3ctestlib/Sources.py", line 269, in merge
    self.addSource(source, ui)
  File "tools/w3ctestlib/Sources.py", line 231, in addSource
    cachedSource.append(source)
  File "tools/w3ctestlib/Sources.py", line 827, in append
    assert self != other and self.relpath == other.relpath
AssertionError
```

Notably:

```
(Pdb) self != other
True
(Pdb) self.sourcepath
['css-ui-3/support/cursors/.htaccess']
(Pdb) other.sourcepath
['css21/i18n/syndata/support/.htaccess']
(Pdb) self.relpath
support/cursors/.htaccess
(Pdb) other.relpath
support/.htaccess
```

@plinss: Trying to look at w3ctestlib, I'm trying to work out what the requirements for `.htaccess` files are. Given the build system preserves support subdirectories, I'm not sure why it's trying to merge these two files?

**Comment by plinss** [comment]
I fixed this in https://hg.csswg.org/dev/w3ctestlib/rev/c4f33306250f 
Sorry I forgot that you were using a different fork of w3ctestlib

**Comment by gsnedders** [comment]
@plinss Ah, no, that's just hg-git not syncing `.hgsubstate`.

**Comment by gsnedders** [comment]
Basically, https://hg.csswg.org/test/rev/469e81a7cc50 didn't get synced.
